version: "3"
services:
  webapp:
    build: .
#    image: ifengniao/xiyoucloud:1.0
    restart: always
    container_name: xiyoucloud
    ports:
      - "8001:8001"
    volumes:
      - /xiyou/xiyoucloud/application-docker.properties:/xiyou/xiyoucloud/application-docker.properties
      - /xiyou/xiyoucloud/.logs:/xiyou/xiyoucloud/.logs
      - /xiyou/nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx
      - postgis
      - redis
      - influxdb
      - emqx
    networks:
      - xiyou-network
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /xiyou/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /xiyou/nginx/conf.d:/etc/nginx/conf.d
      - /xiyou/nginx/log:/var/log/nginx
      - /xiyou/nginx/html:/usr/share/nginx/html
    networks:
      - xiyou-network
  postgis:
    image: postgis/postgis
    restart: always
    container_name: postgis
    ports:
      - "5432:5432"
    volumes:
      - /xiyou/postgis/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=xiyou0#00Admin
      - ALLOW_IP_RANGE=0.0.0.0/0
    networks:
      - xiyou-network
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /xiyou/redis/data:/data
      - /xiyou/redis/conf/redis.conf:/etc/redis/redis.conf
    command: [ "redis-server", "/etc/redis/redis.conf"]
    networks:
      - xiyou-network
  influxdb:
    image: influxdb
    restart: always
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /xiyou/influxdb/lib:/var/lib/influxdb2
      - /xiyou/influxdb/etc:/etc/influxdb2
    networks:
      - xiyou-network
  emqx:
    image: emqx/emqx
    restart: always
    container_name: emqx
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"
    volumes:
      - /xiyou/emqx/emqx.conf:/etc/emqx/emqx.conf
    networks:
      - xiyou-network
networks:
  xiyou-network: